### PR TITLE
Fix blank space issue with empty field

### LINKED ISSUE #129: Fix blank space issue with empty field
`addCompany`, `editCompany`, `addRole`, and `editRole` gives rise to blank space in the company and role cards for empty fields.

### PR DESCRIPTION
**Pull request by petermonky**
Closes #129.

Fixes issue with blank space in company fields by correcting and simplifying empty string handling.

### CODE REVIEW

File: src/main/java/seedu/tinner/ui/CompanyCard.java [hunk 1]
```diff
@@ -64,15 +64,9 @@ public CompanyCard(Company company, int displayedIndex) {
...
-            phone.setManaged(false);
-        }
-        if (addressField == "") {
-            address.setManaged(false);
-        }
-        if (emailField == "") {
-            email.setManaged(false);
-        }
+        phone.setManaged(!phoneField.isEmpty());
+        address.setManaged(!addressField.isEmpty());
```
Comment (kerbysoh) [inline src/main/java/seedu/tinner/ui/CompanyCard.java]: Nice find here to fix the equality of strings check. Possibly need to rectify some merge conflicts after the adding of Stars to indicate Favourite companies.

**Review by kerbysoh — APPROVED** [review]
LGTM!

File: src/main/java/seedu/tinner/ui/CompanyCard.java (hunk 1 above)
Comment (petermonky) [reply src/main/java/seedu/tinner/ui/CompanyCard.java]: Merge conflicts have been resolved, thanks!
